In [ ]:
import pandas as pd
import datetime

In [ ]:
pd

In [ ]:
# 선생님 드라이브 주소 : bit.ly/3qdffr6
# email : eigentrader@naver.com
# mobile : 01077594655

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### - csv 파일을 로드 하자

In [ ]:
data_file2="/content/drive/MyDrive/data/아파트(매매)__실거래가_(20200601_20210531).csv"

In [ ]:
pd.read_csv?? # 도움말

SyntaxError: ignored

In [ ]:
def date_parser(year,day):      
  date=year+day
  return pd.to_datetime(date,format="%Y%m%d")

df= pd.read_csv("/content/drive/MyDrive/data/아파트(매매)__실거래가_(20200601_20210531).csv",
                parse_dates={"계약날짜":["계약년월","계약일"]}, #[6,7] 행번호로도 가능, 계약년월 계약일은 자동으로 삭제
                skiprows=15, encoding='euc-kr',
                index_col="계약날짜", #set_index 역할
                date_parser=date_parser)

In [ ]:
df.head()

                     시군구       번지    본번  부번  ...  층  건축년도        도로명  해제사유발생일
계약날짜                                         ...
2020-08-20  대구광역시 남구 대명동  2542-12  2542  12  ...  6  2014  명덕로20길 34      NaN
2021-02-08  대구광역시 남구 대명동   3022-1  3022   1  ...  2  2002    양지남길 28      NaN
2021-05-01  대구광역시 남구 대명동   3022-1  3022   1  ...  8  2002    양지남길 28      NaN
2020-06-10  대구광역시 남구 대명동     1635  1635   0  ...  4  1980    대명로 117      NaN
2020-06-18  대구광역시 남구 대명동     1635  1635   0  ...  7  1980    대명로 117      NaN

[5 rows x 11 columns]

In [ ]:
for num_string df['거래금액(만원)']
  print(remove(num_string)) # pd.Series -> apply, map

In [ ]:
def remove(num_string):
  return num_string.replace(',','')
df['거래금액(만원)'].map(remove) #apply 가능
#df[['거래금액(만원)']].apply(remove) #-> pd.Dataframe.apply 다름

계약날짜
2020-08-20    21000
2021-02-08    12000
2021-05-01    15500
2020-06-10    26000
2020-06-18    24750
              ...
2020-10-30    25700
2020-11-05    23300
2020-12-09    30000
2021-01-19    25000
2020-12-17    16000
Name: 거래금액(만원), Length: 42523, dtype: object

In [ ]:
df2=df.assign(new_col=df['시군구']+df['번지'].astype(str)+ df['본번'].astype(str),
          new_col2=df['시군구']+df['번지'].astype(str)+ df['본번'].astype(str)) # R과 같은 문법
df2

            계약날짜  ...                 new_col2
0     2020-08-20  ...  대구광역시 남구 대명동2542-122542
1     2021-02-08  ...   대구광역시 남구 대명동3022-13022
2     2021-05-01  ...   대구광역시 남구 대명동3022-13022
3     2020-06-10  ...     대구광역시 남구 대명동16351635
4     2020-06-18  ...     대구광역시 남구 대명동16351635
...          ...  ...                      ...
42518 2020-10-30  ...     대구광역시 중구 태평로1가1-1871
42519 2020-11-05  ...     대구광역시 중구 태평로1가1-1871
42520 2020-12-09  ...     대구광역시 중구 태평로1가1-1871
42521 2021-01-19  ...     대구광역시 중구 태평로1가1-1871
42522 2020-12-17  ...     대구광역시 중구 태평로2가38-438

[42523 rows x 14 columns]

In [ ]:
df=pd.read_csv(data_file2,skiprows=15,encoding='euc-kr')
df

                  시군구       번지    본번   부번  ...  층  건축년도        도로명  해제사유발생일
0        대구광역시 남구 대명동  2542-12  2542   12  ...  6  2014  명덕로20길 34      NaN
1        대구광역시 남구 대명동   3022-1  3022    1  ...  2  2002    양지남길 28      NaN
2        대구광역시 남구 대명동   3022-1  3022    1  ...  8  2002    양지남길 28      NaN
3        대구광역시 남구 대명동     1635  1635    0  ...  4  1980    대명로 117      NaN
4        대구광역시 남구 대명동     1635  1635    0  ...  7  1980    대명로 117      NaN
...               ...      ...   ...  ...  ... ..   ...        ...      ...
42518  대구광역시 중구 태평로1가    1-187     1  187  ...  8  1985    태평로 177      NaN
42519  대구광역시 중구 태평로1가    1-187     1  187  ...  4  1985    태평로 177      NaN
42520  대구광역시 중구 태평로1가    1-187     1  187  ...  6  1985    태평로 177      NaN
42521  대구광역시 중구 태평로1가    1-187     1  187  ...  9  1985    태평로 177      NaN
42522  대구광역시 중구 태평로2가     38-4    38    4  ...  3  1980    태평로 129      NaN

[42523 rows x 13 columns]

### - column에 하나라도 `NaN` 이 있는 컬럼을 드랍하자

In [ ]:
df.dropna(axis='columns',how='any',inplace=True)
df

                  시군구       번지    본번   부번  ... 거래금액(만원)  층  건축년도        도로명
0        대구광역시 남구 대명동  2542-12  2542   12  ...   21,000  6  2014  명덕로20길 34
1        대구광역시 남구 대명동   3022-1  3022    1  ...   12,000  2  2002    양지남길 28
2        대구광역시 남구 대명동   3022-1  3022    1  ...   15,500  8  2002    양지남길 28
3        대구광역시 남구 대명동     1635  1635    0  ...   26,000  4  1980    대명로 117
4        대구광역시 남구 대명동     1635  1635    0  ...   24,750  7  1980    대명로 117
...               ...      ...   ...  ...  ...      ... ..   ...        ...
42518  대구광역시 중구 태평로1가    1-187     1  187  ...   25,700  8  1985    태평로 177
42519  대구광역시 중구 태평로1가    1-187     1  187  ...   23,300  4  1985    태평로 177
42520  대구광역시 중구 태평로1가    1-187     1  187  ...   30,000  6  1985    태평로 177
42521  대구광역시 중구 태평로1가    1-187     1  187  ...   25,000  9  1985    태평로 177
42522  대구광역시 중구 태평로2가     38-4    38    4  ...   16,000  3  1980    태평로 129

[42523 rows x 12 columns]

### - `해제사유발생일`, `번지`, `본번`, `부번` 은 열은 이제 다시는 사용할 일이 없다. 이 열들을 drop 하자.

In [ ]:
df.drop(['번지', '본번', '부번'],axis='columns',inplace=True)
df

                  시군구      단지명  전용면적(㎡)    계약년월  ...  거래금액(만원)  층  건축년도        도로명
0        대구광역시 남구 대명동   EZ-ONE    77.34  202008  ...    21,000  6  2014  명덕로20길 34
1        대구광역시 남구 대명동  강남골든하이츠    83.56  202102  ...    12,000  2  2002    양지남길 28
2        대구광역시 남구 대명동  강남골든하이츠    62.05  202105  ...    15,500  8  2002    양지남길 28
3        대구광역시 남구 대명동    개나리맨션    59.80  202006  ...    26,000  4  1980    대명로 117
4        대구광역시 남구 대명동    개나리맨션    59.80  202006  ...    24,750  7  1980    대명로 117
...               ...      ...      ...     ...  ...       ... ..   ...        ...
42518  대구광역시 중구 태평로1가    태평라이프    54.60  202010  ...    25,700  8  1985    태평로 177
42519  대구광역시 중구 태평로1가    태평라이프    54.60  202011  ...    23,300  4  1985    태평로 177
42520  대구광역시 중구 태평로1가    태평라이프    54.60  202012  ...    30,000  6  1985    태평로 177
42521  대구광역시 중구 태평로1가    태평라이프    54.60  202101  ...    25,000  9  1985    태평로 177
42522  대구광역시 중구 태평로2가     건영맨션    79.09  202012  ...    16,000  3  1980    태평로 129

[42523 rows x 9 columns]

### - column 명을 변경하자

- 계약년월 -> yearmonth,
- 계약일 -> date,
- 시군구 -> address,
- 단지명 -> apt,
- 전용면적(㎡) -> area,
- 거래금액(만원) -> transaction,
- 층 -> floor,
- 건축년도 -> built,
- 도로명 -> road

In [ ]:
rename_map={ "계약년월":'yearmonth',
    "계약일": 'date',
    "시군구":"address",
    "단지명":"apt",
    "전용면적(㎡)":"area",
    "거래금액(만원)":"transaction",
    "층":"floor",
    "건축년도":"built",
    "도로명":"road"}
df.rename(rename_map,axis='columns',inplace=True)
df

              address      apt   area  ...  floor  built       road
0        대구광역시 남구 대명동   EZ-ONE  77.34  ...      6   2014  명덕로20길 34
1        대구광역시 남구 대명동  강남골든하이츠  83.56  ...      2   2002    양지남길 28
2        대구광역시 남구 대명동  강남골든하이츠  62.05  ...      8   2002    양지남길 28
3        대구광역시 남구 대명동    개나리맨션  59.80  ...      4   1980    대명로 117
4        대구광역시 남구 대명동    개나리맨션  59.80  ...      7   1980    대명로 117
...               ...      ...    ...  ...    ...    ...        ...
42518  대구광역시 중구 태평로1가    태평라이프  54.60  ...      8   1985    태평로 177
42519  대구광역시 중구 태평로1가    태평라이프  54.60  ...      4   1985    태평로 177
42520  대구광역시 중구 태평로1가    태평라이프  54.60  ...      6   1985    태평로 177
42521  대구광역시 중구 태평로1가    태평라이프  54.60  ...      9   1985    태평로 177
42522  대구광역시 중구 태평로2가     건영맨션  79.09  ...      3   1980    태평로 129

[42523 rows x 9 columns]

### - `yearmonth`와 `date` 열을 합쳐서 하나로 만들고 pandas 의 시계열 자료형으로 바꾸자

In [ ]:
import datetime

In [ ]:
df["cdate"] = pd.to_datetime(df['yearmonth'].astype('str') + df['date'].astype('str'), format="%Y%m%d")
df

              address      apt   area  ...  built       road      cdate
0        대구광역시 남구 대명동   EZ-ONE  77.34  ...   2014  명덕로20길 34 2020-08-20
1        대구광역시 남구 대명동  강남골든하이츠  83.56  ...   2002    양지남길 28 2021-02-08
2        대구광역시 남구 대명동  강남골든하이츠  62.05  ...   2002    양지남길 28 2021-05-01
3        대구광역시 남구 대명동    개나리맨션  59.80  ...   1980    대명로 117 2020-06-10
4        대구광역시 남구 대명동    개나리맨션  59.80  ...   1980    대명로 117 2020-06-18
...               ...      ...    ...  ...    ...        ...        ...
42518  대구광역시 중구 태평로1가    태평라이프  54.60  ...   1985    태평로 177 2020-10-30
42519  대구광역시 중구 태평로1가    태평라이프  54.60  ...   1985    태평로 177 2020-11-05
42520  대구광역시 중구 태평로1가    태평라이프  54.60  ...   1985    태평로 177 2020-12-09
42521  대구광역시 중구 태평로1가    태평라이프  54.60  ...   1985    태평로 177 2021-01-19
42522  대구광역시 중구 태평로2가     건영맨션  79.09  ...   1980    태평로 129 2020-12-17

[42523 rows x 10 columns]

### - 계약날짜를 년, 월, 날짜로 나누어 새로운 column으로 추가

In [ ]:
df['year'] = df.cdate.dt.year
df['month'] = df.cdate.dt.month
df['day'] = df.cdate.dt.day
df

              address      apt   area  yearmonth  ...      cdate  year  month  day
0        대구광역시 남구 대명동   EZ-ONE  77.34     202008  ... 2020-08-20  2020      8   20
1        대구광역시 남구 대명동  강남골든하이츠  83.56     202102  ... 2021-02-08  2021      2    8
2        대구광역시 남구 대명동  강남골든하이츠  62.05     202105  ... 2021-05-01  2021      5    1
3        대구광역시 남구 대명동    개나리맨션  59.80     202006  ... 2020-06-10  2020      6   10
4        대구광역시 남구 대명동    개나리맨션  59.80     202006  ... 2020-06-18  2020      6   18
...               ...      ...    ...        ...  ...        ...   ...    ...  ...
42518  대구광역시 중구 태평로1가    태평라이프  54.60     202010  ... 2020-10-30  2020     10   30
42519  대구광역시 중구 태평로1가    태평라이프  54.60     202011  ... 2020-11-05  2020     11    5
42520  대구광역시 중구 태평로1가    태평라이프  54.60     202012  ... 2020-12-09  2020     12    9
42521  대구광역시 중구 태평로1가    태평라이프  54.60     202101  ... 2021-01-19  2021      1   19
42522  대구광역시 중구 태평로2가     건영맨션  79.09     202012  ... 2020-12-17  2020     12   17

[42523 rows x 13 columns]

### - 주소를 각각 시, 구, 동 으로 나고 이를 column으로 저장

In [ ]:
df[['city', 'gu', 'dong']] = df.address.str.split(' ', n=2, expand=True)
df

              address      apt   area  yearmonth  ...  day   city  gu   dong
0        대구광역시 남구 대명동   EZ-ONE  77.34     202008  ...   20  대구광역시  남구    대명동
1        대구광역시 남구 대명동  강남골든하이츠  83.56     202102  ...    8  대구광역시  남구    대명동
2        대구광역시 남구 대명동  강남골든하이츠  62.05     202105  ...    1  대구광역시  남구    대명동
3        대구광역시 남구 대명동    개나리맨션  59.80     202006  ...   10  대구광역시  남구    대명동
4        대구광역시 남구 대명동    개나리맨션  59.80     202006  ...   18  대구광역시  남구    대명동
...               ...      ...    ...        ...  ...  ...    ...  ..    ...
42518  대구광역시 중구 태평로1가    태평라이프  54.60     202010  ...   30  대구광역시  중구  태평로1가
42519  대구광역시 중구 태평로1가    태평라이프  54.60     202011  ...    5  대구광역시  중구  태평로1가
42520  대구광역시 중구 태평로1가    태평라이프  54.60     202012  ...    9  대구광역시  중구  태평로1가
42521  대구광역시 중구 태평로1가    태평라이프  54.60     202101  ...   19  대구광역시  중구  태평로1가
42522  대구광역시 중구 태평로2가     건영맨션  79.09     202012  ...   17  대구광역시  중구  태평로2가

[42523 rows x 16 columns]

### - `transaction`(매매금액) 을 숫자형 자료로 변경하자

In [ ]:
#df['transaction'].map(lambda string:string.replace(',',''))
df

              address      apt   area  yearmonth  ...  day   city  gu   dong
0        대구광역시 남구 대명동   EZ-ONE  77.34     202008  ...   20  대구광역시  남구    대명동
1        대구광역시 남구 대명동  강남골든하이츠  83.56     202102  ...    8  대구광역시  남구    대명동
2        대구광역시 남구 대명동  강남골든하이츠  62.05     202105  ...    1  대구광역시  남구    대명동
3        대구광역시 남구 대명동    개나리맨션  59.80     202006  ...   10  대구광역시  남구    대명동
4        대구광역시 남구 대명동    개나리맨션  59.80     202006  ...   18  대구광역시  남구    대명동
...               ...      ...    ...        ...  ...  ...    ...  ..    ...
42518  대구광역시 중구 태평로1가    태평라이프  54.60     202010  ...   30  대구광역시  중구  태평로1가
42519  대구광역시 중구 태평로1가    태평라이프  54.60     202011  ...    5  대구광역시  중구  태평로1가
42520  대구광역시 중구 태평로1가    태평라이프  54.60     202012  ...    9  대구광역시  중구  태평로1가
42521  대구광역시 중구 태평로1가    태평라이프  54.60     202101  ...   19  대구광역시  중구  태평로1가
42522  대구광역시 중구 태평로2가     건영맨션  79.09     202012  ...   17  대구광역시  중구  태평로2가

[42523 rows x 16 columns]

### - `cdate`(계약날짜) 를 새 인덱스로 설정한후 파일로 저장하자

In [ ]:
df.set_index('cdate').to_csv("apt_trade_part2.csv")

In [ ]:
pd.read_csv("apt_trade_part2.csv")

            cdate         address      apt   area  ...  day   city  gu   dong
0      2020-08-20    대구광역시 남구 대명동   EZ-ONE  77.34  ...   20  대구광역시  남구    대명동
1      2021-02-08    대구광역시 남구 대명동  강남골든하이츠  83.56  ...    8  대구광역시  남구    대명동
2      2021-05-01    대구광역시 남구 대명동  강남골든하이츠  62.05  ...    1  대구광역시  남구    대명동
3      2020-06-10    대구광역시 남구 대명동    개나리맨션  59.80  ...   10  대구광역시  남구    대명동
4      2020-06-18    대구광역시 남구 대명동    개나리맨션  59.80  ...   18  대구광역시  남구    대명동
...           ...             ...      ...    ...  ...  ...    ...  ..    ...
42518  2020-10-30  대구광역시 중구 태평로1가    태평라이프  54.60  ...   30  대구광역시  중구  태평로1가
42519  2020-11-05  대구광역시 중구 태평로1가    태평라이프  54.60  ...    5  대구광역시  중구  태평로1가
42520  2020-12-09  대구광역시 중구 태평로1가    태평라이프  54.60  ...    9  대구광역시  중구  태평로1가
42521  2021-01-19  대구광역시 중구 태평로1가    태평라이프  54.60  ...   19  대구광역시  중구  태평로1가
42522  2020-12-17  대구광역시 중구 태평로2가     건영맨션  79.09  ...   17  대구광역시  중구  태평로2가

[42523 rows x 16 columns]